version: "3.7"

services:
  db1:
    build:
      context: .
    restart: always
  server1:
    build:
      context: ./tic-tac-toe/
    volumes:
      - ./tic-tac-toe:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
  app1:
    build:
      context: ./tic-tac-toe-react/
    ports:
      - "3000:3000"
    volumes:
      - ./tic-tac-toe-react:/app
